### ISSUE TITLE
publish to npm or bower

### ISSUE THREAD

**Issue by monolithed** [MrSwitch/notification.js#7]
Bower could not to install the package.
Could you publish the one?

**Comment by MrSwitch** [comment]
Bumped to v0.0.1, hope that should do the trick.

**Comment by monolithed** [comment]
Thanks.

**Comment by wedneyyuri** [comment]
Hi @MrSwitch, could you publish to npm also? We are using browserify/webpack here.

**Comment by MrSwitch** [comment]
done `npm i notification-polyfill`
